[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/internal-analytics-qs/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/.netlify/functions/analytics"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from = "/case-studies/:slug/"
  to = "/case-studies/index.html"
  status = 200

[[redirects]]
  from = "/case-studies/:slug"
  to = "/case-studies/index.html"
  status = 200
