[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/internal-analytics-qs/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/.netlify/functions/analytics"
  [headers.values]
    Cache-Control = "no-store"
